import Container from 'react-bootstrap/Container';
import Table from 'react-bootstrap/Table';

function MyProjects() {
    return (
        <div className="Projects">
            <Container fluid className="block-example border rounded border-dark" >
                <h1 style = {{padding: '10px'}}>Sample Projects</h1>
                <p style = {{padding: '10px'}}>Source code provided upon request.</p>
                <div>
                    <Table responsive="lg">
                        <thead>
                        <tr>
                            <th>Project Title</th>
                            <th>Description</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Five Stage Pipeline CPU (RISC) - VHDL</td>
                            <td>
                                <ul>
                                    <li>Engineered the components for a pipeline CPU using structural VHDL. This includes an ALU, instruction and data memory, full adders, a control unit and more.</li>
                                    <li>Combined these components to form CPU supporting 32-bit MIPS instruction set.</li>
                                    <li>Addressed control and data hazards, ensuring seamless CPU operation.</li> 
                                    <li>Ensured functionality of CPU by creating testbench for each component and by running program on an FPGA and on ModelSim.</li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>Traffic Light System and UART - VHDL</td>
                            <td>
                                <ul>
                                    <li>Implemented a traffic light system utilizing counters, multiplexers, comparators that are controlled by a finite state machine (FSM).</li>
                                    <li>Designed a Universal Asynchronous Receiver Transmitter (UART) which transmitted the state of the traffic light system through the serial ports of a computer and an FPGA.</li>
                                    <li>Engineered two finite state machines for the transmitter datapath and controller datapath of the UART.</li>
                                    <li>Transmitter was in charge of sending an ASCII byte through the serial port and the controller was in charge of preparing the message to send for the transmitter.</li>
                                    <li>Validated the functionality of the entire system through FPGA simulation and waveform simulations generated by ModelSim.</li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>Floating-Point Adder and Multiplier - VHDL</td>
                            <td>
                                <ul>
                                    <li>Designed a floating-point adder and a floating point multiplier using Algorthmic State Machine (ASM) process.</li>
                                    <li>Implemented all components required in both datapaths such as a fixed-point multiplier, a shift register and a comparator.</li>
                                    <li>Engineered both controlpaths using one-hot method for each state box in ASM diagram.</li>
                                    <li>Validated the functionality of the adder and multiplier through FPGA simulation and waveform simulations generated by ModelSim.</li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>Clinics and Patients Mobile App - Android Studio</td>
                            <td>
                                <ul>
                                    <li>Developed an application that allows patients to book an appointment for a specific service offered by a clinic.</li>
                                    <li>Used Firebase to store the data and hashed all the passwords.</li>
                                    <li>Authenticated a user with his email and password.</li>
                                </ul>
                            </td>
                        </tr>
                        </tbody>
                    </Table>
                </div>
            </Container>
        </div>
    );
}

export default MyProjects;